test : test.c
	gcc test.c -o test

sort_file :
	@ls -lhS

find_log :
	@find *.log

delete_lock_file :
	@sudo rm /home/*.lock

create_lock_dummie :
	sudo touch /home/dummy1.lock /home/dummy2.lock /home/dummy3.lock
